trigger:
- main  # Triggers the pipeline on changes to the main branch

pool:
  vmImage: 'ubuntu-latest'  # Using Ubuntu as the build agent OS

jobs:
- job: AlmOctanePipelineStart
  condition: always()
  displayName: 'AlmOctane Pipeline Start'
  steps:
  - task: octane-start-task@2
    inputs:
      OctaneServiceConnection: 'octaneCon2'
      WorkspaceList: '1002'
      CreatePipelineCheckbox: true
  - task: octane-test-runner-start-task@1
    inputs:
      OctaneServiceConnection: 'octaneCon2'
      WorkspaceList: '1002'
      Framework: 'junit'
      
- job: BuildAndTest
  dependsOn:
    - AlmOctanePipelineStart
  displayName: 'Build and Test'
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: Maven@4  # Assuming 'Maven@4' is the newer version available
    displayName: 'Run Maven Clean Install'
    inputs:
      mavenPomFile: 'pom.xml'  # Path to your pom.xml file
      goals: 'clean install'    # Clean the target directory and build the project
      options: '-B'             # Run in batch mode without interactive input

  - task: Maven@4
    displayName: 'Run Maven Tests'
    inputs:
      mavenPomFile: 'pom.xml'
      goals: 'test'             # Run the tests
      options: '-B'

  - task: PublishTestResults@2
    displayName: 'Publish Test Results'
    inputs:
      testResultsFiles: '**/TEST-*.xml'  # Publish the JUnit test results
      testRunTitle: 'Calculator Unit Tests'
      mergeTestResults: true

- job: AlmOctanePipelineEnd
  condition: always()    # Ensures this job runs regardless of the pipeline status
  dependsOn: 
  - 'AlmOctanePipelineStart'
  - 'BuildAndTest'
  displayName: 'AlmOctane Pipeline End'
  steps:
  - task: octane-end-task@2
    inputs:
      OctaneServiceConnection: 'octaneCon2'
      WorkspaceList: '1002'